name: build and publish release image

on:
  # On release events (also when a published release is converted from/to prerelease), push all patterns
  release:
    types: [released, prereleased]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          build-args:
            NEXT_PUBLIC_APP_NAME: "Bee"
            NEXT_PUBLIC_FEATURE_FLAGS: '{ "Knowledge": false, "Files": true, "FunctionTools": true, "Observe": true }'
            NEXT_PUBLIC_ORGANIZATION_ID_DEFAULT: "org_670cc04869ddffe24f4fd70d"
            NEXT_PUBLIC_PROJECT_ID_DEFAULT: "proj_670cc04869ddffe24f4fd70f"
          tags: iambeeagent/bee-ui-local:${{ github.event.release.tag_name }}
